name: Build and push image
on:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-20.04
    env:
      QUAY_ORG: hacbs-release
      QUAY_REPO: release-utils
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Saves RedHat IT Root CA to a file
        shell: bash
        run: |
            mkdir -p pki/certs
            cat > pki/certs/RedHat-IT-Root-CA-Bundle.pem <<CA
            ${{ secrets.REDHAT_IT_ROOT_CA_BUNDLE }}
            CA
      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USER }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Build image and push it to Quay
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile
          no-cache: true
          tags: |
            quay.io/${{ env.QUAY_ORG }}/${{ env.QUAY_REPO }}:main
            quay.io/${{ env.QUAY_ORG }}/${{ env.QUAY_REPO }}:latest
            quay.io/${{ env.QUAY_ORG }}/${{ env.QUAY_REPO }}:${{ github.sha }}
